#!/usr/bin/env python

"""Alternative gyazo script for Ubuntu"""

__author__ = "Nguyen Anh Tien (nguyen.anh.tien@framgia.com)"
__version__ = "1.0.0"

import httplib, mimetypes
import tempfile
import hashlib
import time
import os
import sys

# http://code.activestate.com/recipes/146306-http-client-to-post-using-multipartform-data/
def post_multipart(host, selector, fields, files):
    """
    Post fields and files to an http host as multipart/form-data.
    fields is a sequence of (name, value) elements for regular form fields.
    files is a sequence of (name, filename, value) elements for data to be uploaded as files
    Return the server's response page.
    """
    content_type, body = encode_multipart_formdata(fields, files)
    h = httplib.HTTP(host)
    h.putrequest('POST', selector)
    h.putheader('Content-Type', content_type)
    h.putheader('Host', host)
    h.putheader('Accept', '*/*')
    h.putheader('User-Agent', 'Gyazo/1.0')
    h.putheader('Content-Length', str(len(body)))
    h.endheaders()
    h.send(body)
    errcode, errmsg, headers = h.getreply()
    return h.file.read()

def encode_multipart_formdata(fields, files):
    """
    fields is a sequence of (name, value) elements for regular form fields.
    files is a sequence of (name, filename, value) elements for data to be uploaded as files
    Return (content_type, body) ready for httplib.HTTP instance
    """
    BOUNDARY = '----BOUNDARYBOUNDARY----'
    CRLF = "\r\n"
    L = []
    for (key, value) in fields:
        L.append('--' + BOUNDARY)
        L.append('Content-Disposition: form-data; name="%s"' % key)
        L.append('')
        L.append(value)
    for (key, filename, value) in files:
        L.append('--' + BOUNDARY)
        L.append('Content-Disposition: form-data; name="%s"; filename="%s"' % (key, filename))
        L.append('')
        L.append(value)
    L.append('--' + BOUNDARY + '--')
    L.append('')
    body = CRLF.join(L)
    content_type = 'multipart/form-data; boundary=%s' % BOUNDARY
    return content_type, body

if __name__ == '__main__':
    try:
        temp_name = "%s.png" % hashlib.md5(str(time.time())).hexdigest()
        temp_path = os.path.join(tempfile.gettempdir(), temp_name)

        os.system("gnome-screenshot -a -f %s" % temp_path)
        f = open(temp_path, 'rb')
        data = f.read()
        gyazo_url = post_multipart(
            'gyazo.com',
            '/upload.cgi',
            [('id', '15b7cf85b12f39a6aef93af03cd9f837')],
            [('imagedata', 'gyazo.com', data)]
        )
        os.system("rm %s" % temp_path)
        os.system("xdg-open %s" % gyazo_url)
        print gyazo_url
    except Exception, e:
        print e
        sys.exit(1)
